# Generated by Django 5.2.6 on 2025-10-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_date_de_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
