# Generated by Django 5.0.6 on 2025-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_elementconstitutif_cycles_elementconstitutif_tags'),
        ('users', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='cycles',
            field=models.ManyToManyField(blank=True, help_text="Cycles auxquels l'enseignant est habituellement affilié", related_name='enseignants', to='academics.cycle'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Liste de tags décrivant les spécialités de l'enseignant (ex: ['Finance', 'Mathématiques'])"),
        ),
    ]
