# Generated by Django 5.0.6 on 2025-10-22 21:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('duree_annees', models.PositiveIntegerField(default=3, help_text='Durée théorique du cycle (en années)')),
            ],
        ),
        migrations.CreateModel(
            name='ElementConstitutif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=255)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('coeff_cc', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=4)),
                ('coeff_examen', models.DecimalField(decimal_places=2, default=Decimal('0.70'), max_digits=4)),
                ('obligatoire', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LMDSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_par_annnee_licence', models.PositiveIntegerField(default=60)),
                ('credits_par_annee_master', models.PositiveIntegerField(default=60)),
                ('credits_par_semestre', models.PositiveIntegerField(default=30)),
                ('seuil_conditionnel_l1', models.PositiveIntegerField(default=47, help_text='Crédits min pour passage conditionnel L1')),
                ('seuil_conditionnel_l2', models.PositiveIntegerField(default=38, help_text='Crédits min pour passage conditionnel L2')),
                ('seuil_conditionnel_general', models.PositiveIntegerField(default=45)),
                ('note_min_valid', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=4)),
                ('note_max', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=4)),
                ('credits_toleres_redoublement', models.PositiveIntegerField(default=0, help_text="Nombre de crédits d'échec tolérés (ex: administration)")),
                ('compensation_annuelle_licence', models.BooleanField(default=True)),
                ('abrev_niveaux', models.JSONField(default=dict, help_text='Ex: {"L1":"L1","L2":"L2","L3":"L3","M1":"M1","M2":"M2"}')),
                ('rattrapage_remplace_examen', models.BooleanField(default=True, help_text='Si True: rattrapage remplace uniquement examen. Sinon: remplace moyenne entière quand meilleur.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres LMD',
                'verbose_name_plural': 'Paramètres LMD',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('capacite', models.PositiveIntegerField(default=0)),
                ('type_salle', models.CharField(choices=[('AMPHI', 'Amphithéâtre'), ('LABO', 'Laboratoire'), ('INFO', 'Salle Informatique'), ('TD', 'Salle de TD'), ('AUTRE', 'Autre')], default='TD', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('sigle', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Format AAAA-AAAA, ex: 2024-2025', max_length=9, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_active', models.BooleanField(default=False)),
                ('est_prolongation', models.BooleanField(default=False, help_text="Indique si cette année est une prolongation d'une autre.")),
                ('prolonge', models.ForeignKey(blank=True, help_text='Année académique dont celle-ci est une prolongation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prolongations', to='academics.anneeacademique')),
            ],
            options={
                'verbose_name': 'Année Académique',
                'verbose_name_plural': 'Années Académiques',
                'ordering': ['-nom'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Groupe A, Groupe 1, Amphi 1', max_length=100)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.anneeacademique')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_horaire_total', models.DecimalField(decimal_places=2, help_text='Volume horaire total prévu pour ce cours (ex: 40.00)', max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='academics.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='academics.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='users.enseignant')),
                ('element_constitutif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='academics.elementconstitutif')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'unique_together': {('element_constitutif', 'classe', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='academics.faculte')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='academics.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='academics.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscrits', to='academics.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('etudiant', 'classe', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='1 pour L1, 2 pour L2, etc.')),
                ('code', models.CharField(blank=True, help_text='Ex: L1, L2, M1', max_length=10, null=True)),
                ('nom', models.CharField(blank=True, help_text='Nom affiché ex: Licence 1', max_length=80, null=True)),
                ('credits_theoriques', models.PositiveIntegerField(default=60)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='academics.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='academics.cycle')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='academics.filiere')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='parcours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.parcours'),
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='1 pour S1, 2 pour S2')),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='academics.anneeacademique')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='academics.niveau')),
            ],
            options={
                'unique_together': {('niveau', 'numero', 'annee_academique')},
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='semestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.semestre'),
        ),
        migrations.CreateModel(
            name='SessionCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('type_session', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('Examen', 'Examen'), ('Autre', 'Autre')], default='CM', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.cours')),
                ('salle', models.ForeignKey(blank=True, help_text='Salle de cours', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.salle')),
            ],
            options={
                'verbose_name': 'Session de Cours',
                'verbose_name_plural': 'Sessions de Cours',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=255)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('coefficient', models.PositiveIntegerField(default=1, help_text="Coefficient global de l'UE dans le semestre")),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='academics.semestre')),
            ],
        ),
        migrations.AddField(
            model_name='elementconstitutif',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecs', to='academics.uniteenseignement'),
        ),
        migrations.CreateModel(
            name='UniteEnseignementModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=255)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('obligatoire', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('code',)},
            },
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='modele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.uniteenseignementmodele'),
        ),
        migrations.AddField(
            model_name='faculte',
            name='universite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultes', to='academics.universite'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_cc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_examen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_rattrapage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('normal', 'Normale'), ('rattrapage', 'Rattrapage'), ('final', 'Finalisée')], default='draft', max_length=20)),
                ('element_constitutif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.elementconstitutif')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.inscription')),
            ],
            options={
                'unique_together': {('inscription', 'element_constitutif')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('annee_academique', 'parcours', 'semestre', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='elementconstitutif',
            unique_together={('ue', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='uniteenseignement',
            unique_together={('semestre', 'code')},
        ),
        migrations.CreateModel(
            name='MaquettePedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquettes', to='academics.niveau')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquettes', to='academics.parcours')),
                ('ues_modele', models.ManyToManyField(related_name='maquettes', to='academics.uniteenseignementmodele')),
            ],
            options={
                'unique_together': {('parcours', 'niveau')},
            },
        ),
        migrations.CreateModel(
            name='ValidationUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('validee', models.BooleanField(default=False)),
                ('credits_obtenus', models.PositiveIntegerField(default=0)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations_ue', to='academics.inscription')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='academics.uniteenseignement')),
            ],
            options={
                'unique_together': {('inscription', 'ue')},
            },
        ),
    ]
