# Generated by Django 5.2.6 on 2025-10-07 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Ex: L, M, D', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Ex: 1 pour L1, 2 pour L2')),
                ('nom_complet', models.CharField(help_text='Ex: Licence 1, Master 2', max_length=100)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='academics.cycle')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'unique_together': {('cycle', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Ex: 1 pour S1, 2 pour S2')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='academics.niveau')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'unique_together': {('niveau', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('credits', models.PositiveIntegerField(default=0, help_text='Nombre de crédits ECTS pour cette UE')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='academics.semestre')),
            ],
            options={
                'verbose_name': "Unité d'Enseignement (UE)",
                'verbose_name_plural': "Unités d'Enseignement (UE)",
            },
        ),
        migrations.CreateModel(
            name='ElementConstitutif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('credits', models.PositiveIntegerField(default=0, help_text='Nombre de crédits ECTS pour cette matière')),
                ('coeff_cc', models.DecimalField(decimal_places=2, default=0.3, help_text='Coefficient du Contrôle Continu', max_digits=3)),
                ('coeff_examen', models.DecimalField(decimal_places=2, default=0.7, help_text="Coefficient de l'Examen Final", max_digits=3)),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecs', to='academics.uniteenseignement')),
            ],
            options={
                'verbose_name': 'Élément Constitutif (EC)',
                'verbose_name_plural': 'Éléments Constitutifs (EC)',
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='academics.filiere')),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'unique_together': {('filiere', 'nom')},
            },
        ),
    ]
