# Generated by Django 5.0.6 on 2025-10-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrainte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_contrainte', models.CharField(choices=[('JOUR_BLOQUE', 'Jour entier bloqué (férié, etc.)'), ('INDISPONIBILITE_ENSEIGNANT', "Indisponibilité ponctuelle d'un enseignant"), ('HEURES_MAX_JOUR_ENSEIGNANT', 'Max heures/jour pour un enseignant')], max_length=50)),
                ('date_debut', models.DateTimeField(blank=True, help_text='Début de la période de contrainte', null=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text='Fin de la période de contrainte', null=True)),
                ('jour_semaine', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], help_text='0=Lundi, 1=Mardi, ..., 6=Dimanche', null=True)),
                ('valeur_json', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.enseignant')),
            ],
        ),
    ]
