# Generated by Django 5.2.6 on 2025-10-07 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Format AAAA-AAAA, ex: 2024-2025', max_length=9, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_active', models.BooleanField(default=False, help_text="Indique si c'est l'année académique en cours")),
            ],
            options={
                'verbose_name': 'Année Académique',
                'verbose_name_plural': 'Années Académiques',
                'ordering': ['-nom'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Groupe A, Groupe 1, Amphi 1', max_length=100)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.anneeacademique')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.niveau')),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.parcours')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'unique_together': {('annee_academique', 'parcours', 'niveau', 'nom')},
            },
        ),
    ]
