# Generated by Django 5.0.6 on 2025-10-24 00:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_contrainte'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementconstitutif',
            name='volume_horaire_forfaitaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Volume horaire forfaitaire pour cette matière', max_digits=5),
        ),
        migrations.AlterField(
            model_name='cours',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='academics.classe'),
        ),
    ]
