# Generated by Django 5.0.6 on 2025-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_elementconstitutif_volume_horaire_forfaitaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementconstitutif',
            name='cycles',
            field=models.ManyToManyField(blank=True, help_text='Cycles dans lesquels cette matière est généralement enseignée', related_name='elements_constitutifs', to='academics.cycle'),
        ),
        migrations.AddField(
            model_name='elementconstitutif',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Liste de tags décrivant le contenu de la matière (ex: ['Algèbre', 'Analyse financière'])"),
        ),
    ]
