# Generated by Django 5.2.6 on 2025-10-07 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_cc', models.DecimalField(blank=True, decimal_places=2, help_text='Note de Contrôle Continu', max_digits=4, null=True)),
                ('note_examen', models.DecimalField(blank=True, decimal_places=2, help_text="Note d'Examen Final", max_digits=4, null=True)),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, help_text='Note finale calculée', max_digits=4, null=True)),
                ('date_saisie', models.DateField(auto_now_add=True)),
                ('element_constitutif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.elementconstitutif')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.inscription')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'unique_together': {('inscription', 'element_constitutif')},
            },
        ),
    ]
