# Generated by Django 5.2.6 on 2025-10-08 13:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniteenseignement',
            name='semestre',
        ),
        migrations.AlterField(
            model_name='elementconstitutif',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='elementconstitutif',
            name='coeff_cc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.3'), help_text='Coefficient du Contrôle Continu', max_digits=3),
        ),
        migrations.AlterField(
            model_name='elementconstitutif',
            name='coeff_examen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.7'), help_text="Coefficient de l'Examen Final", max_digits=3),
        ),
        migrations.AlterField(
            model_name='uniteenseignement',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='MaquettePedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semestre')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.uniteenseignement')),
            ],
            options={
                'verbose_name': 'Maquette Pédagogique',
                'verbose_name_plural': 'Maquettes Pédagogiques',
                'unique_together': {('semestre', 'ue')},
            },
        ),
        migrations.AddField(
            model_name='semestre',
            name='ues',
            field=models.ManyToManyField(related_name='semestres', through='academics.MaquettePedagogique', to='academics.uniteenseignement'),
        ),
    ]
