# Generated by Django 5.2.6 on 2025-10-09 15:20

from django.db import migrations

# Now only contains names, as the 'code' field doesn't exist on the Role model.
ROLES = [
    "Étudiant",
    "Enseignant",
    "Responsable Pédagogique",
    "Administrateur",
]

def create_default_roles(apps, schema_editor):
    Role = apps.get_model('roles', 'Role')
    for role_name in ROLES:
        Role.objects.get_or_create(name=role_name)

def delete_default_roles(apps, schema_editor):
    Role = apps.get_model('roles', 'Role')
    Role.objects.filter(name__in=ROLES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles, reverse_code=delete_default_roles),
    ]
